#version: '3.7' i get error

services:
  wallet-manager:
    build: .
    container_name: wallet-manager-app
    ports:
      - "8081:8080"  # Map local port 8081 to container port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/WalletManageDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '!QAZ1qaz'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: wallet-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: '!QAZ1qaz'
      MYSQL_DATABASE: WalletManageDB
    ports:
      - "3306:3306"
    networks:
      - walletnetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  walletnetwork:
    driver: bridge

volumes:
  mysql_data:
    driver: local
